### ISSUE TITLE
feature request: support for Apple Remote A1156

### ISSUE THREAD

**Issue by Pax-nl** [cbrand/esp32-ir-remote#3]
Hi,

I know you last worked on this library 4 years ago. But would it be possible you have a look at: https://en.wikipedia.org/wiki/Apple_Remote

```
The Apple Remote uses a modified NEC IR protocol which consists of a differential PPM encoding on a 1:3 duty cycle 38 kHz 950 nm infrared carrier. There are 32 bits of encoded data between the AGC leader and the stop bit
```

I'm trying to get this remote working, but failing on every attempt.

**Comment by cbrand** [comment]
Hey.
Sorry but without the actual device it would be very hard for me to give it a shot. This kind of stuff is sadly a lot of trial and error for me.

As I do not have access to one I cannot really support you there.
